### ISSUE TITLE
Photo comes up blank.

### ISSUE THREAD

**Issue by m0nst3r7** [Atlas-Lumi/Photo-of-a-Loved-One#1]
Hi, I love the mod and want to try it, but despite putting the mod in the right place and ensuring the Polaroid was edited, the photo still comes up blank. I have no clue how to fix it.
![TheLongDark 7_28_2024 9_39_51 AM](https://github.com/user-attachments/assets/80f83568-6a76-4c87-a400-59e03349e377)

**Comment by Atlas-Lumi** [comment]
Make sure the image file that comes with the mod is not renamed at all, Polaroid.png only.
Other than that, I'm not sure what would cause this

**Comment by TXRANGER2022** [comment]
im still having issues with this and my file is still named Polaroid i made sure that it matched the original size. im not sure what else to try im playing on 2.44
